# syntax=docker/dockerfile:1

FROM node:22-alpine AS dependencies
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

FROM dependencies AS build
WORKDIR /app

ARG VITE_SHOPIFY_STORE_DOMAIN
ARG VITE_SHOPIFY_STOREFRONT_ACCESS_TOKEN
ARG VITE_SHOPIFY_STOREFRONT_API_VERSION
ARG VITE_SHOPIFY_STOREFRONT_ENABLED
ARG VITE_QUOTE_DELIVERY_ENDPOINT

ENV VITE_SHOPIFY_STORE_DOMAIN=${VITE_SHOPIFY_STORE_DOMAIN}
ENV VITE_SHOPIFY_STOREFRONT_ACCESS_TOKEN=${VITE_SHOPIFY_STOREFRONT_ACCESS_TOKEN}
ENV VITE_SHOPIFY_STOREFRONT_API_VERSION=${VITE_SHOPIFY_STOREFRONT_API_VERSION}
ENV VITE_SHOPIFY_STOREFRONT_ENABLED=${VITE_SHOPIFY_STOREFRONT_ENABLED}
ENV VITE_QUOTE_DELIVERY_ENDPOINT=${VITE_QUOTE_DELIVERY_ENDPOINT}

COPY . .
RUN npm run build

FROM caddy:2-alpine AS runtime

ENV PORT=8080
WORKDIR /srv

COPY Caddyfile /etc/caddy/Caddyfile
COPY --from=build /app/dist /usr/share/caddy

EXPOSE 8080

CMD ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]
