export {
  dealerContracts,
  dealerOneContract,
  dealerTwoContract,
  dealerCosts,
  listPrices,
  mountDealerCost,
  mountListPrice,
  navigatorDealerCost,
  navigatorListPrice,
  promotionalBundles,
  quoteBuilderWorkspaceScenarios,
  sirenDealerCost,
  sirenListPrice,
  springMountingBundle,
  type QuoteBuilderWorkspaceScenarioDefinition,
} from './quoteBuilderWorkspaceFixtures';
