import { z } from 'zod';
import type { ShopifyInventoryAdjustment, ShopifyInventoryAdjustmentReason, ShopifyInventoryError, ShopifyInventoryErrorCode, ShopifyInventoryLocation, ShopifyInventoryMapping, ShopifyInventorySyncItem, ShopifyInventorySyncRequest, ShopifyInventorySyncResult, ShopifyInventorySyncStatus } from '@/types/shopifyInventory';
import { inventoryStatusSchema, variantMappingSchema } from './commerce.schema';
import { metadataSchema } from './common.schema';
import { productSchema } from './product.schema';

const nonEmptyString = z.string().min(1);
export const shopifyInventorySyncStatusSchema = z.enum(['draft', 'mapped', 'validated', 'dry-run', 'succeeded', 'failed', 'adapter-unavailable']) satisfies z.ZodType<ShopifyInventorySyncStatus>;
export const shopifyInventoryAdjustmentReasonSchema = z.enum(['inventory-sync', 'manual-count', 'warehouse-reconciliation', 'return', 'correction', 'unknown']) satisfies z.ZodType<ShopifyInventoryAdjustmentReason>;
export const shopifyInventoryErrorCodeSchema = z.enum(['validation-error', 'mapping-error', 'adapter-unavailable', 'missing-sku', 'missing-location', 'unknown']) satisfies z.ZodType<ShopifyInventoryErrorCode>;

export const shopifyInventoryLocationSchema = z.object({ locationId: nonEmptyString, name: nonEmptyString, shopifyLocationId: z.string().nullable().optional(), shopifyLocationGid: z.string().nullable().optional(), priority: z.number().optional(), metadata: metadataSchema.optional() }) as z.ZodType<ShopifyInventoryLocation>;
export const shopifyInventoryAdjustmentSchema = z.object({ sku: nonEmptyString, locationId: nonEmptyString, availableQuantity: z.number().int().min(0), previousQuantity: z.number().int().min(0).optional(), delta: z.number().int().optional(), reason: shopifyInventoryAdjustmentReasonSchema, inventoryItemId: z.string().nullable().optional(), inventoryItemGid: z.string().nullable().optional(), metadata: metadataSchema.optional() }) as z.ZodType<ShopifyInventoryAdjustment>;
export const shopifyInventoryErrorSchema = z.object({ code: shopifyInventoryErrorCodeSchema, message: nonEmptyString, fieldPath: z.string().optional(), productId: z.string().optional(), sku: z.string().optional(), locationId: z.string().optional(), retryable: z.boolean(), metadata: metadataSchema.optional() }) as z.ZodType<ShopifyInventoryError>;
export const shopifyInventorySyncItemSchema = z.object({ productId: nonEmptyString, sku: nonEmptyString, status: shopifyInventorySyncStatusSchema, inventoryStatus: inventoryStatusSchema, locations: z.array(shopifyInventoryLocationSchema), adjustments: z.array(shopifyInventoryAdjustmentSchema), variantMapping: variantMappingSchema.optional(), errors: z.array(shopifyInventoryErrorSchema), metadata: metadataSchema.optional() }) as z.ZodType<ShopifyInventorySyncItem>;
export const shopifyInventoryMappingSchema = z.object({ productId: nonEmptyString, sku: nonEmptyString, shopifyProductId: z.string().nullable().optional(), shopifyProductGid: z.string().nullable().optional(), shopifyVariantId: z.string().nullable().optional(), shopifyVariantGid: z.string().nullable().optional(), inventoryItemId: z.string().nullable().optional(), inventoryItemGid: z.string().nullable().optional(), locationMappings: z.array(z.object({ locationId: nonEmptyString, shopifyLocationId: z.string().nullable().optional(), shopifyLocationGid: z.string().nullable().optional() })), mappedAt: nonEmptyString, warnings: z.array(shopifyInventoryErrorSchema), metadata: metadataSchema.optional() }) as z.ZodType<ShopifyInventoryMapping>;
export const shopifyInventorySyncRequestSchema = z.object({ requestId: nonEmptyString, products: z.array(productSchema).min(1), locations: z.array(shopifyInventoryLocationSchema).min(1), dryRun: z.literal(true), requestedAt: z.string().optional(), source: z.enum(['catalog-service', 'product-data-platform', 'commerce-foundation', 'manual']).optional(), defaultQuantity: z.number().int().min(0).optional(), reason: shopifyInventoryAdjustmentReasonSchema.optional(), metadata: metadataSchema.optional() }) as z.ZodType<ShopifyInventorySyncRequest>;
export const shopifyInventorySyncResultSchema = z.object({ requestId: nonEmptyString, status: shopifyInventorySyncStatusSchema, items: z.array(shopifyInventorySyncItemSchema), mappings: z.array(shopifyInventoryMappingSchema), errors: z.array(shopifyInventoryErrorSchema), syncedAt: z.string().optional(), metadata: metadataSchema.optional() }) as z.ZodType<ShopifyInventorySyncResult>;
