import { z } from 'zod';
import type { ShopifyPriceAdjustment, ShopifyPriceMapping, ShopifyPricingError, ShopifyPricingErrorCode, ShopifyPricingStrategy, ShopifyPricingSyncItem, ShopifyPricingSyncRequest, ShopifyPricingSyncResult, ShopifyPricingSyncStatus } from '@/types/shopifyPricing';
import { priceSchema, variantMappingSchema } from './commerce.schema';
import { metadataSchema, moneySchema } from './common.schema';
import { productSchema } from './product.schema';
import { contractPriceSchema, dealerCostSchema, listPriceSchema, pricingContextSchema, pricingLineInputSchema } from './pricing.schema';

const nonEmptyString = z.string().min(1);
export const shopifyPricingSyncStatusSchema = z.enum(['draft', 'mapped', 'validated', 'dry-run', 'succeeded', 'failed', 'adapter-unavailable']) satisfies z.ZodType<ShopifyPricingSyncStatus>;
export const shopifyPricingStrategySchema = z.enum(['list-price', 'dealer-cost', 'contract-price', 'manual', 'quote-reference']) satisfies z.ZodType<ShopifyPricingStrategy>;
export const shopifyPricingErrorCodeSchema = z.enum(['validation-error', 'mapping-error', 'adapter-unavailable', 'missing-sku', 'missing-price', 'currency-mismatch', 'unknown']) satisfies z.ZodType<ShopifyPricingErrorCode>;

export const shopifyPriceAdjustmentSchema = z.object({ sku: nonEmptyString, strategy: shopifyPricingStrategySchema, price: moneySchema, compareAtPrice: moneySchema.nullable().optional(), previousPrice: moneySchema.nullable().optional(), reason: z.string().optional(), effectiveAt: z.string().optional(), expiresAt: z.string().optional(), metadata: metadataSchema.optional() }) as z.ZodType<ShopifyPriceAdjustment>;
export const shopifyPricingErrorSchema = z.object({ code: shopifyPricingErrorCodeSchema, message: nonEmptyString, fieldPath: z.string().optional(), productId: z.string().optional(), sku: z.string().optional(), retryable: z.boolean(), metadata: metadataSchema.optional() }) as z.ZodType<ShopifyPricingError>;
export const shopifyPriceMappingSchema = z.object({ productId: nonEmptyString, sku: nonEmptyString, strategy: shopifyPricingStrategySchema, price: priceSchema, shopifyProductId: z.string().nullable().optional(), shopifyProductGid: z.string().nullable().optional(), shopifyVariantId: z.string().nullable().optional(), shopifyVariantGid: z.string().nullable().optional(), mappedAt: nonEmptyString, warnings: z.array(shopifyPricingErrorSchema), metadata: metadataSchema.optional() }) as z.ZodType<ShopifyPriceMapping>;
export const shopifyPricingSyncItemSchema = z.object({ productId: nonEmptyString, sku: nonEmptyString, status: shopifyPricingSyncStatusSchema, strategy: shopifyPricingStrategySchema, price: priceSchema, adjustment: shopifyPriceAdjustmentSchema, variantMapping: variantMappingSchema.optional(), errors: z.array(shopifyPricingErrorSchema), metadata: metadataSchema.optional() }) as z.ZodType<ShopifyPricingSyncItem>;
export const shopifyPricingSyncRequestSchema = z.object({ requestId: nonEmptyString, products: z.array(productSchema).min(1), dryRun: z.literal(true), requestedAt: z.string().optional(), source: z.enum(['pricing-domain', 'dealer-contract-resolution', 'commerce-foundation', 'manual']).optional(), strategy: shopifyPricingStrategySchema.optional(), pricingContext: pricingContextSchema.optional(), pricingLines: z.array(pricingLineInputSchema).optional(), listPrices: z.array(listPriceSchema).optional(), dealerCosts: z.array(dealerCostSchema).optional(), contractPrices: z.array(contractPriceSchema).optional(), defaultCurrencyCode: z.string().optional(), metadata: metadataSchema.optional() }) as z.ZodType<ShopifyPricingSyncRequest>;
export const shopifyPricingSyncResultSchema = z.object({ requestId: nonEmptyString, status: shopifyPricingSyncStatusSchema, items: z.array(shopifyPricingSyncItemSchema), mappings: z.array(shopifyPriceMappingSchema), errors: z.array(shopifyPricingErrorSchema), syncedAt: z.string().optional(), metadata: metadataSchema.optional() }) as z.ZodType<ShopifyPricingSyncResult>;
